//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xam.Applications.GradientEditor.Controls {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xam.Applications.GradientEditor.Controls.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current stop must be between {0} and {1}, inclusive.
        /// </summary>
        public static string ArgumentException_CurrentEditStop {
            get {
                return ResourceManager.GetString("ArgumentException_CurrentEditStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum stops must be greater than minimim stops.
        /// </summary>
        public static string ArgumentException_MaximumStops {
            get {
                return ResourceManager.GetString("ArgumentException_MaximumStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum stops must be at least 2.
        /// </summary>
        public static string ArgumentException_MinimumStops {
            get {
                return ResourceManager.GetString("ArgumentException_MinimumStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected stop count must be betwwen MinStops and MaxStops, inclusive.
        /// </summary>
        public static string ArgumentException_SelectedStopsCount {
            get {
                return ResourceManager.GetString("ArgumentException_SelectedStopsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy the gradient brush xaml to the clipboard.
        /// </summary>
        public static string CommandDescriptionCopyXaml {
            get {
                return ResourceManager.GetString("CommandDescriptionCopyXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Decrease the range of the gradient selector.
        /// </summary>
        public static string CommandDescriptionDecreaseGradientRange {
            get {
                return ResourceManager.GetString("CommandDescriptionDecreaseGradientRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Increase the range of the gradient selector.
        /// </summary>
        public static string CommandDescriptionIncreaseGradientRange {
            get {
                return ResourceManager.GetString("CommandDescriptionIncreaseGradientRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset the gradient parameters to their initial state. Does not affect colors..
        /// </summary>
        public static string CommandDescriptionReset {
            get {
                return ResourceManager.GetString("CommandDescriptionReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift gradient colors to the left.
        /// </summary>
        public static string CommandDescriptionShiftColorsLeft {
            get {
                return ResourceManager.GetString("CommandDescriptionShiftColorsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift gradient colors to the right.
        /// </summary>
        public static string CommandDescriptionShiftColorsRight {
            get {
                return ResourceManager.GetString("CommandDescriptionShiftColorsRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spread the gradient stops evenly within the gradient range.
        /// </summary>
        public static string CommandDescriptionSpreadGradientStops {
            get {
                return ResourceManager.GetString("CommandDescriptionSpreadGradientStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display stop dividers.
        /// </summary>
        public static string Label_DisplayStopDividers {
            get {
                return ResourceManager.GetString("Label_DisplayStopDividers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End point X.
        /// </summary>
        public static string Label_EndPointX {
            get {
                return ResourceManager.GetString("Label_EndPointX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End point Y.
        /// </summary>
        public static string Label_EndPointY {
            get {
                return ResourceManager.GetString("Label_EndPointY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start point X.
        /// </summary>
        public static string Label_StartPointX {
            get {
                return ResourceManager.GetString("Label_StartPointX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start point Y.
        /// </summary>
        public static string Label_StartPointY {
            get {
                return ResourceManager.GetString("Label_StartPointY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters reset.
        /// </summary>
        public static string OperationMessageReset {
            get {
                return ResourceManager.GetString("OperationMessageReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Xaml copied to clipboard.
        /// </summary>
        public static string OperationMessageXamlCopiedToClipboard {
            get {
                return ResourceManager.GetString("OperationMessageXamlCopiedToClipboard", resourceCulture);
            }
        }
    }
}
